FROM ghcr.io/rust-cross/rust-musl-cross:x86_64-musl

ARG RUST_TOOLCHAIN=

RUN if [ -n "${RUST_TOOLCHAIN}" ]; then \
        rustup toolchain list | grep -qx "${RUST_TOOLCHAIN}-x86_64-unknown-linux-gnu" || \
        rustup toolchain install "${RUST_TOOLCHAIN}" --profile minimal --target x86_64-unknown-linux-musl; \
        rustup default "${RUST_TOOLCHAIN}"; \
    fi

WORKDIR /home/rust/src
